### ISSUE TITLE
Colon missing on lock screen.

### ISSUE THREAD

**Issue by mbednarek360** [Magisk-Modules-Repo/exo2-font-magisk#1]
After installing font the colon on the lock screen for the time appears to bs missing.

Picture:
https://photos.app.goo.gl/KNUTU4aCTij0qFUl2

**Comment by P1N2O** [comment]
Will fix it in the next update

**Comment by P1N2O** [comment]
@mbednarek360 Please update to the latest version and report.

**Comment by Olit2000** [comment]
The last release (2.0.4) broke it again
